### ISSUE TITLE
Opening Youtube.com in a new tab redirects to the mobile version

### ISSUE THREAD

**Issue by ErenYanic** [odebroqueville/contextSearch#202]
When I try to go to Youtube, the link that should normally be there: https://www.youtube.com/feed/subscriptions
But this plugin redirects to the mobile youtube app: https://m.youtube.com/feed/subscriptions

As you can see in the screenshots I've attached, this problem appeared with today's update and frankly, it's disgusting to see youtube like this. I really can't understand why such an extension would need to interfere with something like redirecting to mobile youtube in Firefox and how the developers released such an update. I think it should be fixed as soon as possible, I think it is a very useful add-on, but I don't think I will use it in this state. The add-on asked me for additional permissions today and I approved it directly that's my fault. I don't find it logical for add-on developers to ask for more and more permissions from the user, it is better to keep the permissions to a minimum.

![Image](https://github.com/user-attachments/assets/688dc1d5-df1e-4a72-9ca6-3571f7cffb85)

![Image](https://github.com/user-attachments/assets/9a139b77-fba4-45fe-8597-cfa98826eebc)

**Comment by odebroqueville** [comment]
Thank you for reporting this bug. There's a lot you don't understand about how the extension works! To render a web page nicely in the sidebar, I have to change the user agent requesting the page to get the mobile version. However, this should only be carried out when opening the web page in the sidebar. Version 6.0.1 should fix this. Please consider making a donation if you find the extension useful and  avoid using words like "disgusting"!

**Comment by lenormf** [comment]
Thank you for the quick update!

Unfortunately, `v6.0.1` doesn’t fix it for me, the Youtube page still gets redirected.

I made sure to clear all cookies, as I’ve seen online it may force a redirection, and only disabling the addon fixes it.

Firefox `v136.0.1` (64bits), Ubuntu (20 Focal).

**Comment by ErenYanic** [comment]
The disgusting part was not add-on, it was the first time I saw youtube like that and it is too bad to use. So mobile youtube looks disgusting. If I had no intention of helping add-on and I found it disgusting, I would have uninstalled it and moved on. I looked for what was causing the problem and when I suspected add-ons, I activated all 30 different add-ons one by one to find the one that was causing the problem and I started a thread here to make you aware of this problem. Otherwise, I could write a bad comment on the firefox extension page and move on, but that would not be helpful to anyone, especially disrespectful to the developer of an add-on that I actually use. The language I used may have been harsh, forgive me for that, that was not my intention.

**Comment by ErenYanic** [comment]
> Thank you for reporting this bug. There's a lot you don't understand about how the extension works! To render a web page nicely in the sidebar, I have to change the user agent requesting the page to get the mobile version. However, this should only be carried out when opening the web page in the sidebar. Version 6.0.1 should fix this. Please consider making a donation if you find the extension useful and avoid using words like "disgusting"! Concerning permissions, I invite you to read issue 201. I've also made most permissions optional to give users as much control as possible.
> <img alt="Image" width="656" src="https://private-user-images.githubusercontent.com/4818315/422404759-cfe56e78-d83e-43a1-b643-8cd589ee683f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE5Mzc5MTIsIm5iZiI6MTc0MTkzNzYxMiwicGF0aCI6Ii80ODE4MzE1LzQyMjQwNDc1OS1jZmU1NmU3OC1kODNlLTQzYTEtYjY0My04Y2Q1ODllZTY4M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTRUMDczMzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjJhMDYxNmVhNmQ5OWVjZTliMjExNmJlZWZlNmM0NjFlY2JlY2QxMWU4YzkwZDI1ODI4MDNlZjAwZjM3MjFlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g_hR1IrEGM2vy4B1uzKX9prNIa9pLpUhd6RpN1L3lpU">

The disgusting part was not add-on, it was the first time I saw youtube like that and it is too bad to use. So mobile youtube looks disgusting. If I had no intention of helping add-on and I found it disgusting, I would have uninstalled it and moved on. I looked for what was causing the problem and when I suspected add-ons, I activated all 30 different add-ons one by one to find the one that was causing the problem and I started a thread here to make you aware of this problem. Otherwise, I could write a bad comment on the firefox extension page and move on, but that would not be helpful to anyone, especially disrespectful to the developer of an add-on that I actually use. The language I used may have been harsh, forgive me for that, that was not my intention.

**Comment by odebroqueville** [comment]
@ErenYanic Happy to hear that the issue is solved on your end. I did find that you were being a bit harsh calling the mobile version of YouTube "disgusting". It's a strong word that conveys a sense of repulsion. "ugly" might have been more appropriate!  Your message also came across as a bit of a threat if the problem wasn't addressed. Lastly, this extension has many features with many options. I'm a solo hobbyist web developer, so please understand that I can't possibly test all the different hardware and software scenarios. I test the extension and decide at some point that it is "good enough" to be released. But, I obviously rely on the user community to help report bugs that I've missed. I hope this clarifies. Have a nice weekend.

@lenormf Strange things happen in Firefox! I was able to reproduce your issue yesterday, but not any more today! If it helps, I'm using Firefox Developer Edition 137.0b5 (aarch64). Are you still encountering this issue?

**Comment by lenormf** [comment]
I am still reproducing the issue.

I restarted the browser, disabled all add-ons and leaving only Context Search enabled.

Disabling Context Search always fixes it, without touching the cookies or site data.

**Comment by odebroqueville** [comment]
Honestly, I don't understand why you're being redirected. I'm not able to reproduce this on macOS. You should only be redirected if the url you type ends with #_sidebar, e.g. https://youtube.com/whatever#_sidebar. In this case, you will be redirected, so you'll want to make sure that the url doesn't get auto-completed with #_sidebar. There are 2 other things I'd suggest you try: allow Context Search to run in private mode. Then open a private window and type youtube.com. See what happens. Finally, if you're still encountering issues, I'd remove the extension and re-install it anew.

**Comment by lenormf** [comment]
I performed the experiment with the private window, and Youtube worked as expected, even with Context Search on.

I don’t know what it was, probably something to do with the cache, but it’s gone now.

Feel free to close the issue, thanks for the help!
